image: python:3.7.4-alpine

stages:
  - deploy

before_script:
  - apk --no-cache add --virtual gcc
  - python3 -m pip install --upgrade pip setuptools wheel twine
  - python setup.py sdist

#deploy-staging:
#  stage: deploy
#  when: manual
#  variables:
#    TWINE_USERNAME: $STAGING_USERNAME
#    TWINE_PASSWORD: $STAGING_PASSWORD
#  script:
#    - twine upload --repository-url $TEST_PYPI_REPOSITORY_URL dist/*
#  only:
#    - develop
#    - master
#
#deploy-prod:
#  stage: deploy
#  when: manual
#  variables:
#    TWINE_USERNAME: $STAGING_USERNAME
#    TWINE_PASSWORD: $STAGING_PASSWORD
#  script:
#    - twine upload dist/*
#  only:
#    - tags

