stages:
  - build
  - test
  - deploy

variables:
  IMAGE: python3.7-alpine

before_script:
  - pip install --upgrade setuptools wheel twine
  - python setup.py sdsit

deploy-staging:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - twine upload --repository-url $TEST_PYPI_REPOSITORY_URL dist/*
  only:
    - develop
    - master

deploy-prod:
  stage: deploy
  when: manual
  variables:
    TWINE_USERNAME: $STAGING_USERNAME
    TWINE_PASSWORD: $STAGING_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags

