image: python:3.7.4-alpine

stages:
  - test

before_script:
  - apk add --virtual build-deps gcc python-dev musl-dev
  - python3 -m pip install --upgrade pip
  # - pip install setuptools wheel
  - pip install twine
  - python setup.py sdist


test:
  stage: test
  script:
    - python setup.py test

#deploy-staging:
#  stage: deploy
#  when: manual
#  variables:
#    TWINE_USERNAME: $STAGING_USERNAME
#    TWINE_PASSWORD: $STAGING_PASSWORD
#  script:
#    - twine upload --repository-url $TEST_PYPI_REPOSITORY_URL dist/*
#  only:
#    - develop
#    - master
#
#deploy-prod:
#  stage: deploy
#  when: manual
#  variables:
#    TWINE_USERNAME: $STAGING_USERNAME
#    TWINE_PASSWORD: $STAGING_PASSWORD
#  script:
#    - twine upload dist/*
#  only:
#    - tags

